//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Updater.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Updater.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please close the game application..
        /// </summary>
        internal static string GameWindow {
            get {
                return ResourceManager.GetString("GameWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is already running..
        /// </summary>
        internal static string SingleInstance {
            get {
                return ResourceManager.GetString("SingleInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading updater.
        /// </summary>
        internal static string UserState1 {
            get {
                return ResourceManager.GetString("UserState1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading ({0}/{1}).
        /// </summary>
        internal static string UserState2 {
            get {
                return ResourceManager.GetString("UserState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed.
        /// </summary>
        internal static string UserState3 {
            get {
                return ResourceManager.GetString("UserState3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting.
        /// </summary>
        internal static string UserState4 {
            get {
                return ResourceManager.GetString("UserState4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction failed.
        /// </summary>
        internal static string UserState5 {
            get {
                return ResourceManager.GetString("UserState5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating.
        /// </summary>
        internal static string UserState6 {
            get {
                return ResourceManager.GetString("UserState6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building archive.
        /// </summary>
        internal static string UserState7 {
            get {
                return ResourceManager.GetString("UserState7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update completed.
        /// </summary>
        internal static string UserState8 {
            get {
                return ResourceManager.GetString("UserState8", resourceCulture);
            }
        }
    }
}
